/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    "signal-pricing": SignalPricing;
    users: User;
    media: Media;
    lessons: Lesson;
    modules: Module;
    courses: Course;
    enrollments: Enrollment;
    "telegram-groups": TelegramGroup;
    transactions: Transaction;
    notifications: Notification;
    "lesson-progress": LessonProgress;
    "module-progress": ModuleProgress;
    "payload-kv": PayloadKv;
    "payload-jobs": PayloadJob;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    "signal-pricing": SignalPricingSelect<false> | SignalPricingSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    "telegram-groups": TelegramGroupsSelect<false> | TelegramGroupsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    "lesson-progress": LessonProgressSelect<false> | LessonProgressSelect<true>;
    "module-progress": ModuleProgressSelect<false> | ModuleProgressSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    "currency-exchange-rate": CurrencyExchangeRate;
    "payload-jobs-stats": PayloadJobsStat;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    "currency-exchange-rate":
      | CurrencyExchangeRateSelect<false>
      | CurrencyExchangeRateSelect<true>;
    "payload-jobs-stats":
      | PayloadJobsStatsSelect<false>
      | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendWelcomeEmail: TaskSendWelcomeEmail;
      sendPromotionalWelcomeEmail: TaskSendPromotionalWelcomeEmail;
      "cleanup-notification": TaskCleanupNotification;
      sendTelegramLink: TaskSendTelegramLink;
      enqueueVideo: TaskEnqueueVideo;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage pricing tiers for signal subscriptions and lifetime access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signal-pricing".
 */
export interface SignalPricing {
  id: number;
  /**
   * e.g., Monthly Signals, Quarterly Signals, Lifetime Access
   */
  title: string;
  /**
   * Auto-generated from title (kept read-only for consistency)
   */
  slug: string;
  /**
   * Check if this is a free tier (price will be ignored)
   */
  isFree?: boolean | null;
  /**
   * Short tagline shown under the plan name
   */
  description: string;
  /**
   * Price in base units (e.g., 97000 for NGN97000)
   */
  price: number;
  /**
   * Currency code (default USD)
   */
  currency: "NGN" | "USD";
  /**
   * Display text, e.g., "Per Month", "Per Quarterly", "Per Semi Annual"
   */
  period: "/month" | "/3 months" | "/6 semiannual" | "/12 Annual" | "/lifetime";
  /**
   * Highlight this tier with "Most Popular" badge (only one recommended)
   */
  popular?: boolean | null;
  /**
   * Lower numbers appear first on the pricing page
   */
  sortOrder?: number | null;
  features?:
    | {
      text: string;
      id?: string | null;
    }[]
    | null;
  /**
   * Button text, e.g., "Get Quarterly (Most Popular)"
   */
  cta: string;
  /**
   * Uncheck to hide from pricing page without deleting
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  first_name: string;
  last_name?: string | null;
  role?: ("admin" | "customer" | "bot") | null;
  phone?: string | null;
  avatar?: (number | null) | Media;
  plan?: (number | null) | SignalPricing;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
      id: string;
      createdAt?: string | null;
      expiresAt: string;
    }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * Central media library. Public files are visible to everyone. Private files are restricted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Public = visible on listings & to everyone. Private = restricted.
   */
  type: "public" | "private" | "paid";
  /**
   * Tracks media processing/transcoding lifecycle.
   */
  processingStatus: "pending" | "processing" | "completed" | "failed";
  uploadedBy: number | User;
  updatedBy?: (number | null) | User;
  /**
   * Required for images (accessibility). Optional for videos and documents.
   */
  alt?: string | null;
  /**
   * HLS master playlist path (e.g. /video/abc123/master.m3u8). Set automatically after transcoding.
   */
  streamPath?: string | null;
  /**
   * Thumbnail image path (e.g. /video/abc123/thumbnail.jpg). Set automatically after transcoding.
   */
  videoThumbnail?: string | null;
  /**
   * Video duration in seconds. Set automatically after transcoding.
   */
  durationSeconds?: number | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  /**
   * Auto-generated from title – edit carefully for SEO URLs.
   */
  slug?: string | null;
  description: string;
  module: number | Module;
  /**
   * Display order within the module.
   */
  order: number;
  video: number | Media;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  /**
   * Auto-generated from title – edit carefully for SEO URLs.
   */
  slug?: string | null;
  course: number | Course;
  /**
   * Display order within the course.
   */
  order: number;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Auto-generated from title – edit carefully for SEO URLs.
   */
  slug: string;
  description: string;
  isPublished?: boolean | null;
  moduleCount?: number | null;
  /**
   * Set automatically when the course is first published.
   */
  publishedAt?: string | null;
  price: number;
  isFree?: boolean | null;
  /**
   * Currency code (default: USD)
   */
  currency: "NGN" | "USD";
  thumbnail: number | Media;
  /**
   * If enabled, users must complete all lessons in a section before accessing the next.
   */
  requireSequentialCompletion?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user enrollments in courses – free or paid, with watch time analytics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  user: number | User;
  course: number | Course;
  userEmail?: string | null;
  courseTitle?: string | null;
  enrolledAt: string;
  status: "enrolled" | "in-progress" | "completed";
  progress?: number | null;
  /**
   * Total hours watched (decimal). Auto-calculated from lesson watch time.
   */
  watchHours?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Telegram groups for signal delivery and community engagement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "telegram-groups".
 */
export interface TelegramGroup {
  id: number;
  /**
   * Display name for the Telegram group (e.g., 'Main Signal Group').
   */
  name: string;
  /**
   * Unique identifier for the Telegram group chat.
   */
  chatId: string;
  /**
   * Associate this Telegram group with a specific signal pricing package.
   */
  package?: (number | null) | SignalPricing;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  transactionId: string;
  user: number | User;
  /**
   * Determines which product was purchased
   */
  type: "course" | "signal-plan";
  /**
   * The course that was purchased (lifetime access)
   */
  course?: (number | null) | Course;
  /**
   * The signal plan or subscription that was purchased
   */
  signalPlan?: (number | null) | SignalPricing;
  /**
   * Indicates whether the Telegram/signal group invitation has been sent to the user
   */
  invitationSent?: boolean | null;
  amount: number;
  currency: string;
  paymentMethod: "korapay" | "nowpayments";
  status: "pending" | "succeeded" | "failed" | "refunded" | "cancelled";
  isRecurring?: boolean | null;
  billingInterval?:
    | ("/month" | "/3 months" | "/6 semiannual" | "/12 Annual" | "/lifetime")
    | null;
  nextBillingDate?: string | null;
  paymentDate?: string | null;
  metadata?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User notifications (signals, courses, community, billing, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type:
    | "signal"
    | "course"
    | "community"
    | "billing"
    | "announcement"
    | "achievement";
  title: string;
  message: string;
  /**
   * Optional internal or external URL (e.g. /signals/123, /courses/module-4)
   */
  link?: string | null;
  /**
   * User has seen this notification
   */
  read?: boolean | null;
  readAt?: string | null;
  metadata?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user progress for each lesson
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress".
 */
export interface LessonProgress {
  id: number;
  user: number | User;
  moduleProgress: number | ModuleProgress;
  lesson: number | Lesson;
  watchedSeconds?: number | null;
  status: "in-progress" | "completed";
  lastWatchedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user progress for each module
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-progress".
 */
export interface ModuleProgress {
  id: number;
  user: number | User;
  enrollment: number | Enrollment;
  module: number | Module;
  watchedSeconds?: number | null;
  status: "in-progress" | "completed";
  lastWatchedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
      executedAt: string;
      completedAt: string;
      taskSlug:
        | "inline"
        | "sendWelcomeEmail"
        | "sendPromotionalWelcomeEmail"
        | "cleanup-notification"
        | "sendTelegramLink"
        | "enqueueVideo";
      taskID: string;
      input?:
        | {
          [k: string]: unknown;
        }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      output?:
        | {
          [k: string]: unknown;
        }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      state: "failed" | "succeeded";
      error?:
        | {
          [k: string]: unknown;
        }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      id?: string | null;
    }[]
    | null;
  taskSlug?:
    | (
      | "inline"
      | "sendWelcomeEmail"
      | "sendPromotionalWelcomeEmail"
      | "cleanup-notification"
      | "sendTelegramLink"
      | "enqueueVideo"
    )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
      relationTo: "signal-pricing";
      value: number | SignalPricing;
    } | null)
    | ({
      relationTo: "users";
      value: number | User;
    } | null)
    | ({
      relationTo: "media";
      value: number | Media;
    } | null)
    | ({
      relationTo: "lessons";
      value: number | Lesson;
    } | null)
    | ({
      relationTo: "modules";
      value: number | Module;
    } | null)
    | ({
      relationTo: "courses";
      value: number | Course;
    } | null)
    | ({
      relationTo: "enrollments";
      value: number | Enrollment;
    } | null)
    | ({
      relationTo: "telegram-groups";
      value: number | TelegramGroup;
    } | null)
    | ({
      relationTo: "transactions";
      value: number | Transaction;
    } | null)
    | ({
      relationTo: "notifications";
      value: number | Notification;
    } | null)
    | ({
      relationTo: "lesson-progress";
      value: number | LessonProgress;
    } | null)
    | ({
      relationTo: "module-progress";
      value: number | ModuleProgress;
    } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signal-pricing_select".
 */
export interface SignalPricingSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isFree?: T;
  description?: T;
  price?: T;
  currency?: T;
  period?: T;
  popular?: T;
  sortOrder?: T;
  features?:
    | T
    | {
      text?: T;
      id?: T;
    };
  cta?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  first_name?: T;
  last_name?: T;
  role?: T;
  phone?: T;
  avatar?: T;
  plan?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
      id?: T;
      createdAt?: T;
      expiresAt?: T;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  type?: T;
  processingStatus?: T;
  uploadedBy?: T;
  updatedBy?: T;
  alt?: T;
  streamPath?: T;
  videoThumbnail?: T;
  durationSeconds?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
      thumbnail?:
        | T
        | {
          url?: T;
          width?: T;
          height?: T;
          mimeType?: T;
          filesize?: T;
          filename?: T;
        };
      card?:
        | T
        | {
          url?: T;
          width?: T;
          height?: T;
          mimeType?: T;
          filesize?: T;
          filename?: T;
        };
      large?:
        | T
        | {
          url?: T;
          width?: T;
          height?: T;
          mimeType?: T;
          filesize?: T;
          filename?: T;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  module?: T;
  order?: T;
  video?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  course?: T;
  order?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  isPublished?: T;
  moduleCount?: T;
  publishedAt?: T;
  price?: T;
  isFree?: T;
  currency?: T;
  thumbnail?: T;
  requireSequentialCompletion?: T;
  createdBy?: T;
  updatedBy?: T;
  meta?:
    | T
    | {
      title?: T;
      description?: T;
      image?: T;
    };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  userEmail?: T;
  courseTitle?: T;
  enrolledAt?: T;
  status?: T;
  progress?: T;
  watchHours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "telegram-groups_select".
 */
export interface TelegramGroupsSelect<T extends boolean = true> {
  name?: T;
  chatId?: T;
  package?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  transactionId?: T;
  user?: T;
  type?: T;
  course?: T;
  signalPlan?: T;
  invitationSent?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  status?: T;
  isRecurring?: T;
  billingInterval?: T;
  nextBillingDate?: T;
  paymentDate?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  link?: T;
  read?: T;
  readAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress_select".
 */
export interface LessonProgressSelect<T extends boolean = true> {
  user?: T;
  moduleProgress?: T;
  lesson?: T;
  watchedSeconds?: T;
  status?: T;
  lastWatchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-progress_select".
 */
export interface ModuleProgressSelect<T extends boolean = true> {
  user?: T;
  enrollment?: T;
  module?: T;
  watchedSeconds?: T;
  status?: T;
  lastWatchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
      executedAt?: T;
      completedAt?: T;
      taskSlug?: T;
      taskID?: T;
      input?: T;
      output?: T;
      state?: T;
      error?: T;
      id?: T;
    };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  hero: {
    heading: string;
    subheading?: string | null;
    image?: (number | null) | Media;
  };
  mission: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  vision?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  team?:
    | {
      name: string;
      role: string;
      bio?: string | null;
      image?: (number | null) | Media;
      socialLinks?:
        | {
          platform?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
        | null;
      id?: string | null;
    }[]
    | null;
  cta?: {
    text?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Single global object that defines the active exchange rate (e.g. USD → NGN). Used site-wide for pricing display and conversions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currency-exchange-rate".
 */
export interface CurrencyExchangeRate {
  id: number;
  /**
   * Base currency (what users pay in)
   */
  baseCurrency: string;
  /**
   * Target currency (local display currency)
   */
  targetCurrency: string;
  /**
   * 1 baseCurrency = X targetCurrency
   */
  exchangeRate: number;
  lastUpdated?: string | null;
  updatedBy?: (number | null) | User;
  source?: ("manual" | "korapay" | "nowpayments" | "external" | "bank") | null;
  /**
   * Why was this rate updated? (optional)
   */
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
      [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
      heading?: T;
      subheading?: T;
      image?: T;
    };
  mission?: T;
  vision?: T;
  team?:
    | T
    | {
      name?: T;
      role?: T;
      bio?: T;
      image?: T;
      socialLinks?:
        | T
        | {
          platform?: T;
          url?: T;
          id?: T;
        };
      id?: T;
    };
  cta?:
    | T
    | {
      text?: T;
      buttonLabel?: T;
      buttonLink?: T;
    };
  meta?:
    | T
    | {
      title?: T;
      description?: T;
      image?: T;
    };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currency-exchange-rate_select".
 */
export interface CurrencyExchangeRateSelect<T extends boolean = true> {
  baseCurrency?: T;
  targetCurrency?: T;
  exchangeRate?: T;
  lastUpdated?: T;
  updatedBy?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendWelcomeEmail".
 */
export interface TaskSendWelcomeEmail {
  input: {
    userEmail: string;
    userFullname: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendPromotionalWelcomeEmail".
 */
export interface TaskSendPromotionalWelcomeEmail {
  input: {
    userEmail: string;
    userFullname: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanup-notification".
 */
export interface TaskCleanupNotification {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendTelegramLink".
 */
export interface TaskSendTelegramLink {
  input: {
    email: string;
    firstName: string;
    userId: number;
    isCourse: boolean;
    PurchasedPackage: string;
    courseLink?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEnqueueVideo".
 */
export interface TaskEnqueueVideo {
  input: {
    filename: string;
    mediaId: number;
    prefix: string;
    secret: string;
    serviceUrl: string;
    generateThumbnail: boolean;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
